# Generated by Django 5.0.1 on 2024-01-19 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kasbi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hodim', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media')),
                ('name', models.CharField(max_length=20)),
                ('malumot', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turi', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('malumot', models.TextField()),
                ('img', models.ImageField(upload_to='media')),
                ('twit', models.CharField(max_length=40)),
                ('face', models.CharField(max_length=40)),
                ('inst', models.CharField(max_length=40)),
                ('tele', models.CharField(max_length=40)),
                ('date', models.DateField()),
                ('kasbi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfiles.kasbi')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media')),
                ('name', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=30)),
                ('client', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('link', models.CharField(max_length=40)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfiles.type')),
            ],
        ),
    ]
