# Generated by Django 5.0.1 on 2024-01-24 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0003_subscribe'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubPort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
